repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
    - id: forbid-crlf
    - id: remove-crlf
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=7000']
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.2
  hooks:
  - id: clang-format
